# Imports

In [1]:
import numpy as np
from genetic_algorithm import GeneticAlgorithmTSPTW

# Load data

In [2]:
# Distance matrix
distance_matrix = np.array([
    [0, 1, 8, 9, 3, 2, 4, 6],  # From A
    [1, 0, 7, 4, 1, 3, 9, 2],  # From B
    [8, 7, 0, 6, 8, 2, 4, 5],  # From C
    [9, 4, 6, 0, 9, 3, 1, 1],  # From D
    [3, 1, 8, 9, 0, 4, 2, 7],  # From E
    [2, 3, 2, 3, 4, 0, 6, 3],  # From F
    [4, 9, 4, 1, 2, 6, 0, 5],  # From G
    [6, 2, 5, 1, 7, 3, 5, 0]   # From H
])

# Time windows for each city (A, B, C, D, E, F, G, H)
time_windows = {
    'A': (0, 100),
    'B': (3, 12),
    'C': (32, 40),
    'D': (15, 24),
    'E': (3, 6),
    'F': (6, 10),
    'G': (25, 30),
    'H': (50, 52)
}

In [3]:
# Display the loaded data
print("Distance Matrix:")
print(distance_matrix)
print("\nTime Windows:")
for city, window in time_windows.items():
    print(f"City {city}: Min = {window[0]}, Max = {window[1]}")

Distance Matrix:
[[0 1 8 9 3 2 4 6]
 [1 0 7 4 1 3 9 2]
 [8 7 0 6 8 2 4 5]
 [9 4 6 0 9 3 1 1]
 [3 1 8 9 0 4 2 7]
 [2 3 2 3 4 0 6 3]
 [4 9 4 1 2 6 0 5]
 [6 2 5 1 7 3 5 0]]

Time Windows:
City A: Min = 0, Max = 100
City B: Min = 3, Max = 12
City C: Min = 32, Max = 40
City D: Min = 15, Max = 24
City E: Min = 3, Max = 6
City F: Min = 6, Max = 10
City G: Min = 25, Max = 30
City H: Min = 50, Max = 52


# Run the Genetic Algorithm

In [4]:
# Initialize the GA
ga = GeneticAlgorithmTSPTW(
    distance_matrix=distance_matrix,
    time_windows=time_windows,
    population_size=100,
    mutation_rate=0.1,
    generations=300
)

# Run the algorithm
best_route, best_cost = ga.run()

#  Check for feasible solution

In [5]:
penalty = ga.calc_penalty(best_route)

if penalty == 0:
    print("Feasible solution found with no time window violations!")
else:
    print("No feasible solution without violations.")

No feasible solution without violations.


# Solution

In [6]:
distance, penalty, total_cost = ga.eval_route(best_route)

city_names = list(time_windows.keys())
route = [city_names[i] for i in best_route]
print("Best Route:", ' → '.join(route))

print(f"\n Evaluation:")
print(f"- Total Distance: {distance}")
print(f"- Time Window Violations (Penalty): {penalty}")
print(f"- Total Cost (Distance + Penalty): {total_cost}")

Best Route: A → F → C → G → D → H → B → E → A

 Evaluation:
- Total Distance: 16
- Time Window Violations (Penalty): 6
- Total Cost (Distance + Penalty): 22
